name: Fly Deploy
on: 
  push:
    branches:
      - develop
    paths:
    - 'Dices/**'
  pull_request:
    branches:
      - develop
    paths:
    - 'Dices/**'
jobs:
  deploy:
    name: Deploy Rolling Dices API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          working-directory: ./Dices
      - run: flyctl deploy --remote-only
        working-directory: ./Dices
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
